// <auto-generated />
using System;
using EnemPrep.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EnemPrep.Infrastructure.Migrations
{
    [DbContext(typeof(EnemPrepDbContext))]
    [Migration("20260501233933_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EnemPrep.Domain.Entities.Alternativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("Alternativas", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Assunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.ToTable("Assuntos", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Conquista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("PontosZ")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Conquistas", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.DesafioDiario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataDesafio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("XPRecompensa")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("DesafiosDiarios", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Livro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoConteudo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UrlCapa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("MateriaId");

                    b.HasIndex("TipoConteudo");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.LivroPagina", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LivroId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumeroProprio")
                        .HasColumnType("integer");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("LivroId", "NumeroProprio")
                        .IsUnique();

                    b.ToTable("LivrosPaginas");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.LivroTema", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LivroId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("PaginaFinal")
                        .HasColumnType("integer");

                    b.Property<int>("PaginaInicial")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.ToTable("LivrosTemas");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Materia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Materias", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.PerfilUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NomeApresentacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("PerfisUsuario", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.PlanoEstudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("PlanosEstudo", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.PlanoEstudoItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssuntoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataPrevista")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlanoEstudoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("PlanoEstudoId");

                    b.ToTable("PlanosEstudoItens", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Questao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssuntoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<string>("Explicacao")
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid?>("LivroId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LivroTemaId")
                        .HasColumnType("uuid");

                    b.Property<string>("VideoExplicacaoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.HasIndex("LivroId");

                    b.HasIndex("LivroTemaId");

                    b.ToTable("Questoes", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.RespostaSimulado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlternativaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TentativaSimuladoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlternativaId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("TentativaSimuladoId");

                    b.ToTable("RespostasSimulado", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Simulado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AnoReferencia")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<TimeSpan>("DuracaoMaxima")
                        .HasColumnType("interval");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Simulados", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.SimuladoQuestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SimuladoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("SimuladoId");

                    b.ToTable("SimuladosQuestoes", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.StreakUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DiasConsecutivos")
                        .HasColumnType("integer");

                    b.Property<int>("MaiorStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UltimaAtividade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("StreaksUsuario", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.TentativaQuestao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Acertou")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AlternativaSelecionadaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<int>("TempoGastoSegundos")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlternativaSelecionadaId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId", "QuestaoId");

                    b.ToTable("TentativasQuestao", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.TentativaSimulado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NotaTotalBruta")
                        .HasColumnType("integer");

                    b.Property<Guid>("SimuladoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SimuladoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TentativasSimulado", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PerfilUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilUsuarioId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.UsuarioConquista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConquistaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("DataObtencao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConquistaId");

                    b.HasIndex("UsuarioId", "ConquistaId")
                        .IsUnique();

                    b.ToTable("UsuarioConquistas", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.VideoAula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssuntoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("DuracaoSegundos")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("UrlVideo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AssuntoId");

                    b.ToTable("VideoAulas", (string)null);
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Alternativa", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Questao", "Questao")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Assunto", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Materia", "Materia")
                        .WithMany("Assuntos")
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.DesafioDiario", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Livro", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Materia", "Materia")
                        .WithMany()
                        .HasForeignKey("MateriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Materia");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.LivroPagina", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Livro", "Livro")
                        .WithMany("Paginas")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.LivroTema", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Livro", "Livro")
                        .WithMany("Temas")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.PlanoEstudo", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PlanosEstudo")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.PlanoEstudoItem", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Assunto", "Assunto")
                        .WithMany()
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnemPrep.Domain.Entities.PlanoEstudo", "PlanoEstudo")
                        .WithMany("Itens")
                        .HasForeignKey("PlanoEstudoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");

                    b.Navigation("PlanoEstudo");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Questao", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Assunto", "Assunto")
                        .WithMany("Questoes")
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnemPrep.Domain.Entities.Livro", "Livro")
                        .WithMany("Questoes")
                        .HasForeignKey("LivroId");

                    b.HasOne("EnemPrep.Domain.Entities.LivroTema", "LivroTema")
                        .WithMany("Questoes")
                        .HasForeignKey("LivroTemaId");

                    b.Navigation("Assunto");

                    b.Navigation("Livro");

                    b.Navigation("LivroTema");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.RespostaSimulado", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Alternativa", "Alternativa")
                        .WithMany()
                        .HasForeignKey("AlternativaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnemPrep.Domain.Entities.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnemPrep.Domain.Entities.TentativaSimulado", "TentativaSimulado")
                        .WithMany("Respostas")
                        .HasForeignKey("TentativaSimuladoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alternativa");

                    b.Navigation("Questao");

                    b.Navigation("TentativaSimulado");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.SimuladoQuestao", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnemPrep.Domain.Entities.Simulado", "Simulado")
                        .WithMany("Questoes")
                        .HasForeignKey("SimuladoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");

                    b.Navigation("Simulado");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.StreakUsuario", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Streak")
                        .HasForeignKey("EnemPrep.Domain.Entities.StreakUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.TentativaQuestao", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Alternativa", "AlternativaSelecionada")
                        .WithMany()
                        .HasForeignKey("AlternativaSelecionadaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EnemPrep.Domain.Entities.Questao", "Questao")
                        .WithMany("Tentativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnemPrep.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tentativas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlternativaSelecionada");

                    b.Navigation("Questao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.TentativaSimulado", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Simulado", "Simulado")
                        .WithMany("Tentativas")
                        .HasForeignKey("SimuladoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnemPrep.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Simulado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.PerfilUsuario", "PerfilUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerfilUsuario");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.UsuarioConquista", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Conquista", "Conquista")
                        .WithMany("UsuariosConquista")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnemPrep.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.VideoAula", b =>
                {
                    b.HasOne("EnemPrep.Domain.Entities.Assunto", "Assunto")
                        .WithMany("VideoAulas")
                        .HasForeignKey("AssuntoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assunto");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Assunto", b =>
                {
                    b.Navigation("Questoes");

                    b.Navigation("VideoAulas");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Conquista", b =>
                {
                    b.Navigation("UsuariosConquista");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Livro", b =>
                {
                    b.Navigation("Paginas");

                    b.Navigation("Questoes");

                    b.Navigation("Temas");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.LivroTema", b =>
                {
                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Materia", b =>
                {
                    b.Navigation("Assuntos");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.PerfilUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.PlanoEstudo", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Questao", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Simulado", b =>
                {
                    b.Navigation("Questoes");

                    b.Navigation("Tentativas");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.TentativaSimulado", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("EnemPrep.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("PlanosEstudo");

                    b.Navigation("Streak");

                    b.Navigation("Tentativas");
                });
#pragma warning restore 612, 618
        }
    }
}
